version: '2'

services:
  sharedb:
    build: .
    image: telcosys/sharedb:v1
    restart: unless-stopped
    networks:
      - rproxy
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sharedb"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:sharedb.$RPROXYDOMAIN"
    container_name: sharedb
    hostname: sharedb


networks:
  rproxy:
    external: true
