version: '3'

services:
  kuzzle:
    image: kuzzleio/kuzzle:2
    restart: unless-stopped
    networks:
      - rproxy
   # ports:
   #   - "7512:7512"
   #   - "1883:1883"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__protocols__mqtt__enabled=true
      - NODE_ENV=production
    volumes:
      - ./kuzzlerc:/var/app/.kuzzlerc
      - ./plugins:/var/app/plugins/enabled
    labels:
      - "traefik.enable=true"
      - "traefik.backend=kuzzle"
      - "traefik.port=7512"
      - "traefik.frontend.rule=Host:kuzzle.cugli.net"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"  # other projects
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.browserXSSFilter=false"
      - "traefik.frontend.headers.frameDeny=false"
      - "traefik.frontend.headers.contentTypeNosniff=false"
    container_name: kuzzle

  redis:
    image: redis:5
    restart: unless-stopped
    networks:
      - rproxy
    container_name: kuzzle-redis

  elasticsearch:
    image: kuzzleio/elasticsearch:7.4.0
    restart: unless-stopped
    networks:
      - rproxy
    ulimits:
      nofile: 65536
    container_name: kuzzle-db


networks:
  rproxy:
    external: true


