version: "3.3"

services:
  traefik:
    image: "traefik:2.5"
    container_name: traefik
    network_mode: "host"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./rules:/etc/traefik/rules:ro"
      - "/data/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    tmpfs: /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashhttp.entrypoints=web"
      - "traefik.http.routers.dashhttp.rule=Host(`rproxy.domain.ar`)"
      - "traefik.http.routers.dashhttp.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`rproxy.domain.ar`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=dash:$$apr1$$hgbu.........................yP1"

  whoami:
    image: "traefik/whoami"
    container_name: whoami
    hostname: whoami
    restart: unless-stopped
    networks:
      - rproxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoamihttp.entrypoints=web"
      - "traefik.http.routers.whoamihttp.rule=Host(`whoami.domain.ar`)"
      - "traefik.http.routers.whoamihttp.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.whoamihttps.entrypoints=websecure"
      - "traefik.http.routers.whoamihttps.rule=Host(`whoami.domain.ar`)"
      - "traefik.http.routers.whoamihttps.tls=true"
      - "traefik.http.routers.whoamihttps.tls.certresolver=letsencrypt"

networks:
  rproxy:
    external: true

