version: '2'

services:
  httpbin:
    image: citizenstig/httpbin:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=httpbin"
      - "traefik.frontend.rule=Host:bot.cugli.life"
    container_name: httpbin



