version: "3"
services:
    shinobi:
        image: shinobisystems/shinobi:dev
        container_name: shinobi
        environment:
           - PLUGIN_KEYS={"Tensorflow":"$TENSORFLOW_PLUGIN_KEY"}
           - SSL_ENABLED=false
        volumes:
           - ./config:/config
           - ./autoload:/home/Shinobi/libs/customAutoLoad
           - ./database:/var/lib/mysql
           - ./videos:/home/Shinobi/videos
           - ./plugins:/home/Shinobi/plugins
           - /dev/shm/Shinobi/streams:/dev/shm/streams
           - /etc/localtime:/etc/localtime:ro
        ports:
           - 8181:8080
        restart: unless-stopped

    shinobiplugintensorflow:
        image: shinobisystems/shinobi-tensorflow:latest
        container_name: shinobi-tensorflow
        environment:
          - PLUGIN_KEY=$TENSORFLOW_PLUGIN_KEY
          - PLUGIN_HOST=shinobi
        volumes:
          - ./tensorflow:/config
          - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped



