version: '2'

services:
  bin:
    image: dexafree/ghostbin
    restart: unless-stopped
    networks:
      - rproxy
    volumes:
      - data:/data
      - logs:/logs
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bin"
      - "traefik.port=8619"
      - "traefik.frontend.rule=Host:bin.$RPROXYDOMAIN"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=false"  # other projects
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.browserXSSFilter=false"
      - "traefik.frontend.headers.frameDeny=false"
      - "traefik.frontend.headers.contentTypeNosniff=false"
    container_name: bin
    hostname: bin

volumes:
  data:
  logs:

networks:
  rproxy:
    external: true

